# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='رقم الطلب')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=16, verbose_name='رقم الموبايل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('processing', 'قيد التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('refunded', 'مسترجع')], default='pending', max_length=16, verbose_name='الحالة')),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوع'), ('partially_paid', 'مدفوع جزئيًا'), ('paid', 'مدفوع'), ('partially_refunded', 'مسترجع جزئيًا'), ('refunded', 'مسترجع بالكامل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='unpaid', max_length=20, verbose_name='حالة الدفع')),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', 'لم يُجهّز'), ('partially_fulfilled', 'مجهّز جزئيًا'), ('fulfilled', 'مجهّز'), ('returned', 'مرتجع')], default='unfulfilled', max_length=24, verbose_name='حالة التجهيز')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='مفتاح التكرار')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي الفرعي')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصم')),
                ('coupon_code', models.CharField(blank=True, default='', max_length=32, verbose_name='كود الخصم')),
                ('shipping_method_label', models.CharField(blank=True, default='', max_length=80, verbose_name='طريقة الشحن')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='تكلفة الشحن')),
                ('installation_requested', models.BooleanField(default=False, verbose_name='طلب التركيب')),
                ('installation_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='تكلفة التركيب')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='مستخرجة من الإجمالي الشامل ولا تُضاف إليه.', max_digits=12, verbose_name='ضريبة القيمة المضافة (مستخرجة)')),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1400'), max_digits=5, verbose_name='نسبة الضريبة وقت الطلب')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('used_placeholder_rates', models.BooleanField(default=False, help_text='سجل تدقيق: أُنشئ الطلب بأسعار شحن/تركيب غير معتمدة تجاريًا.', verbose_name='استخدم أسعارًا تطويرية')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='قبل الشروط في')),
                ('placed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='أنشئ في')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='ألغي في')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=80, verbose_name='رقم التتبع')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.customerprofile', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-placed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=16, verbose_name='الموبايل')),
                ('governorate_key', models.CharField(max_length=40, verbose_name='مفتاح المحافظة')),
                ('governorate_name', models.CharField(max_length=80, verbose_name='المحافظة')),
                ('area_key', models.CharField(blank=True, default='', max_length=60, verbose_name='مفتاح المنطقة')),
                ('area_name', models.CharField(blank=True, default='', max_length=80, verbose_name='المنطقة')),
                ('city', models.CharField(max_length=80, verbose_name='المدينة')),
                ('street', models.CharField(max_length=140, verbose_name='الشارع')),
                ('building', models.CharField(max_length=24, verbose_name='المبنى')),
                ('landmark', models.CharField(blank=True, default='', max_length=100, verbose_name='علامة مميزة')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عنوان طلب',
                'verbose_name_plural': 'عناوين الطلبات',
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40, verbose_name='النوع')),
                ('from_status', models.CharField(blank=True, default='', max_length=16, verbose_name='من حالة')),
                ('to_status', models.CharField(blank=True, default='', max_length=16, verbose_name='إلى حالة')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'حدث طلب',
                'verbose_name_plural': 'أحداث الطلبات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160, verbose_name='اسم المنتج')),
                ('product_slug', models.SlugField(blank=True, default='', max_length=120, verbose_name='معرف المنتج')),
                ('variant_label', models.CharField(blank=True, default='', max_length=80, verbose_name='الخيار')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('image_path', models.CharField(blank=True, default='', max_length=255, verbose_name='مسار الصورة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='سعر الوحدة')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='الكمية')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي السطر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.order', verbose_name='الطلب')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.productvariant', verbose_name='الخيار')),
            ],
            options={
                'verbose_name': 'سطر طلب',
                'verbose_name_plural': 'أسطر الطلبات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('body', models.TextField(verbose_name='النص')),
                ('is_customer_visible', models.BooleanField(default=False, verbose_name='مرئية للعميل')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'ملاحظة طلب',
                'verbose_name_plural': 'ملاحظات الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-placed_at'], name='order_status_placed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-placed_at'], name='order_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', Decimal('0'))), name='order_grand_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', Decimal('0'))), name='order_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_total__gte', Decimal('0'))), name='order_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0'))), name='order_line_unit_price_non_negative'),
        ),
    ]
