# Generated by Django 5.2.16 on 2026-08-04 13:06

import apps.accounts.models
import apps.accounts.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('full_name', models.CharField(max_length=120, verbose_name='الاسم بالكامل')),
                ('phone', models.CharField(blank=True, default='', max_length=16, validators=[apps.accounts.validators.validate_egyptian_mobile], verbose_name='رقم الموبايل')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='تم توثيق الرقم')),
                ('email_verified', models.BooleanField(default=False, verbose_name='تم توثيق البريد')),
                ('accepts_marketing', models.BooleanField(default=False, verbose_name='يقبل الرسائل التسويقية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف عميل',
                'verbose_name_plural': 'ملفات العملاء',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('label', models.CharField(blank=True, default='', max_length=60, verbose_name='اسم العنوان')),
                ('full_name', models.CharField(max_length=120, verbose_name='اسم المستلم')),
                ('phone', models.CharField(max_length=16, validators=[apps.accounts.validators.validate_egyptian_mobile], verbose_name='رقم الموبايل')),
                ('city', models.CharField(max_length=80, verbose_name='المدينة أو المركز')),
                ('street', models.CharField(max_length=140, verbose_name='الشارع والعنوان التفصيلي')),
                ('building', models.CharField(max_length=24, verbose_name='رقم المبنى')),
                ('landmark', models.CharField(blank=True, default='', max_length=100, verbose_name='علامة مميزة')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='shipping.servicearea')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='shipping.governorate')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customerprofile')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_verified', True), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='unique_verified_customer_phone'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer',), name='unique_default_address_per_customer'),
        ),
    ]
