# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('title', models.CharField(max_length=160, verbose_name='العنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='الصورة')),
                ('legacy_image_path', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='الرابط')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ في')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=16, verbose_name='رقم الموبايل')),
                ('subject', models.CharField(max_length=120, verbose_name='الموضوع')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الرد'), ('spam', 'غير مرغوبة')], default='new', max_length=16, verbose_name='الحالة')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='المفتاح')),
                ('heading', models.CharField(blank=True, default='', max_length=160, verbose_name='العنوان')),
                ('eyebrow', models.CharField(blank=True, default='', max_length=120, verbose_name='عنوان فرعي')),
                ('body', models.TextField(blank=True, default='', verbose_name='النص')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'قسم الصفحة الرئيسية',
                'verbose_name_plural': 'أقسام الصفحة الرئيسية',
                'ordering': ['position', 'key'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('source', models.CharField(blank=True, default='', max_length=60, verbose_name='المصدر')),
                ('confirmed', models.BooleanField(default=False, verbose_name='مؤكد')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'اشتراك النشرة',
                'verbose_name_plural': 'اشتراكات النشرة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='الشعار')),
                ('legacy_image_path', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='المعرف')),
                ('title', models.CharField(max_length=160, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, default='', verbose_name='المحتوى')),
                ('seo_title', models.CharField(blank=True, default='', max_length=160, verbose_name='عنوان SEO')),
                ('seo_description', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف SEO')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشورة')),
            ],
            options={
                'verbose_name': 'صفحة ثابتة',
                'verbose_name_plural': 'الصفحات الثابتة',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('question', models.CharField(max_length=255, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('page', models.CharField(blank=True, default='', max_length=40, verbose_name='الصفحة')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('products', models.ManyToManyField(blank=True, related_name='faqs', to='catalog.product', verbose_name='المنتجات')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('label', models.CharField(max_length=120, verbose_name='النص')),
                ('href', models.CharField(blank=True, default='', max_length=255, verbose_name='الرابط')),
                ('route_name', models.CharField(blank=True, default='', help_text='اسم مسار Django مفضّل على الرابط الثابت.', max_length=80, verbose_name='اسم المسار')),
                ('icon', models.CharField(blank=True, default='', max_length=60, verbose_name='الأيقونة')),
                ('group', models.CharField(choices=[('primary', 'التنقل الرئيسي'), ('utility', 'أدوات'), ('footer', 'التذييل')], default='primary', max_length=16, verbose_name='المجموعة')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.navigationitem', verbose_name='العنصر الأعلى')),
            ],
            options={
                'verbose_name': 'عنصر تنقل',
                'verbose_name_plural': 'عناصر التنقل',
                'ordering': ['group', 'position', 'id'],
            },
        ),
    ]
