# Generated by Django 5.2.16 on 2026-08-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='المحتوى المنسّق'),
        ),
    ]
