# Generated by Django 5.2.16 on 2026-08-08 13:14

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homesection_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[apps.core.uploads.validate_image_upload], verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', validators=[apps.core.uploads.validate_image_upload], verbose_name='الشعار'),
        ),
    ]
