# Generated by Django 5.2.16 on 2026-08-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_banner_image_alter_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='العنوان (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, default='', verbose_name='الإجابة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='السؤال (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='body_en',
            field=models.TextField(blank=True, default='', verbose_name='النص (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='eyebrow_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='عنوان فرعي (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='العنوان (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='النص (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='body_en',
            field=models.TextField(blank=True, default='', verbose_name='المحتوى (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='seo_description_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='وصف SEO (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='عنوان SEO (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='العنوان (إنجليزي)'),
        ),
    ]
