# Generated by Django 5.2.16 on 2026-08-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_banner_title_en_faq_answer_en_faq_question_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='data_en',
            field=models.JSONField(blank=True, default=dict, verbose_name='المحتوى المنسّق (إنجليزي)'),
        ),
    ]
