# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1400'), help_text='أسعار الكتالوج شاملة الضريبة؛ تُستخرج الضريبة ولا تُضاف.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='نسبة ضريبة القيمة المضافة')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='حد الشحن المجاني')),
                ('currency_code', models.CharField(default='EGP', max_length=3, verbose_name='رمز العملة')),
                ('currency_label', models.CharField(default='ج.م', max_length=8, verbose_name='رمز العرض')),
                ('currency_decimal_places', models.PositiveSmallIntegerField(default=0, verbose_name='خانات عشرية')),
                ('order_number_prefix', models.CharField(default='ZK', max_length=8, verbose_name='بادئة رقم الطلب')),
                ('max_line_quantity', models.PositiveSmallIntegerField(default=9, help_text='يطابق حد الواجهة الحالي (1–9).', verbose_name='أقصى كمية للسطر')),
                ('cart_ttl_days', models.PositiveSmallIntegerField(default=30, verbose_name='مدة صلاحية السلة (أيام)')),
                ('reservation_ttl_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة حجز المخزون (دقائق)')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='حد المخزون المنخفض')),
                ('prototype_notice', models.TextField(blank=True, default='', verbose_name='تنويه العرض')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
    ]
