# Generated by Django 5.2.16 on 2026-08-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='currency_label_en',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='رمز العرض (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='prototype_notice_en',
            field=models.TextField(blank=True, default='', verbose_name='تنويه العرض (إنجليزي)'),
        ),
    ]
