# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='الكود')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='الوصف')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=16, verbose_name='نوع الخصم')),
                ('value', models.DecimalField(decimal_places=2, help_text='نسبة مئوية (مثل 5) أو مبلغ ثابت بالجنيه.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='القيمة')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='سقف اختياري للخصم النسبي.', max_digits=12, null=True, verbose_name='أقصى خصم')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ في')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام الكلي')),
                ('per_customer_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام لكل عميل')),
                ('minimum_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='أقل إجمالي مطلوب')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('is_demo', models.BooleanField(default=False, help_text='لا يمثل عرضًا تجاريًا حقيقيًا؛ للتطوير فقط.', verbose_name='كود عرض تجريبي')),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category', verbose_name='تصنيفات محددة')),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product', verbose_name='منتجات محددة')),
            ],
            options={
                'verbose_name': 'كود خصم',
                'verbose_name_plural': 'أكواد الخصم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الخصم')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.coupon', verbose_name='الكود')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='accounts.customerprofile', verbose_name='العميل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'استخدام كود',
                'verbose_name_plural': 'استخدامات الأكواد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', Decimal('0'))), name='coupon_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='coupon_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit__isnull', True), ('times_used__lte', models.F('usage_limit')), _connector='OR'), name='coupon_usage_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'order'), name='unique_coupon_per_order'),
        ),
    ]
