# Generated by Django 5.2.16 on 2026-08-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الوصف (إنجليزي)'),
        ),
    ]
