# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='الكود')),
                ('label', models.CharField(max_length=80, verbose_name='الاسم')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='الوصف')),
                ('icon_path', models.CharField(blank=True, default='', max_length=200, verbose_name='الأيقونة')),
                ('notice', models.CharField(blank=True, default='', help_text='يُعرض عندما تكون الطريقة غير مفعّلة بعد.', max_length=255, verbose_name='تنويه')),
                ('is_active', models.BooleanField(default=True, verbose_name='معروضة')),
                ('is_integrated', models.BooleanField(default=False, help_text='لا يوجد أي تكامل مع مزود دفع في هذا الإصدار.', verbose_name='متصلة بمزود')),
                ('collects_on_delivery', models.BooleanField(default=False, verbose_name='تحصيل عند الاستلام')),
                ('is_manual', models.BooleanField(default=False, verbose_name='تسجيل يدوي بواسطة الفريق')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('state', models.CharField(choices=[('pending', 'قيد الانتظار'), ('authorised', 'محجوز'), ('captured', 'محصّل'), ('failed', 'فشل'), ('cancelled', 'ملغي'), ('partially_refunded', 'مسترجع جزئيًا'), ('refunded', 'مسترجع')], default='pending', max_length=20, verbose_name='الحالة')),
                ('provider_reference', models.CharField(blank=True, default='', max_length=128, verbose_name='مرجع المزود')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='مفتاح التكرار')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='حُصّل في')),
                ('failed_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='سبب الفشل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='الطلب')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='الطريقة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40, verbose_name='النوع')),
                ('provider_event_id', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='معرف حدث المزود')),
                ('payload_digest', models.CharField(blank=True, default='', max_length=128, verbose_name='بصمة الحمولة')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'حدث دفع',
                'verbose_name_plural': 'أحداث الدفع',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('state', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'منفّذ'), ('failed', 'فشل')], default='pending', max_length=16, verbose_name='الحالة')),
                ('provider_reference', models.CharField(blank=True, default='', max_length=128, verbose_name='مرجع المزود')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'استرجاع',
                'verbose_name_plural': 'الاسترجاعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'state'], name='payment_order_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='refund_amount_positive'),
        ),
    ]
