# Generated by Django 5.2.16 on 2026-08-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_refund_cap_constraint_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الوصف (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='notice_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='تنويه (إنجليزي)'),
        ),
    ]
