# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('on_hand', models.IntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('reserved', models.IntegerField(default=0, verbose_name='الكمية المحجوزة')),
                ('low_stock_threshold', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد المخزون المنخفض')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='catalog.productvariant', verbose_name='الخيار')),
            ],
            options={
                'verbose_name': 'رصيد مخزون',
                'verbose_name_plural': 'أرصدة المخزون',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(verbose_name='التغيير')),
                ('reason', models.CharField(choices=[('purchase', 'توريد'), ('reserve', 'حجز'), ('release', 'إلغاء حجز'), ('fulfill', 'تنفيذ'), ('return', 'مرتجع'), ('adjust', 'تسوية'), ('damaged', 'تالف'), ('lost', 'مفقود'), ('correction', 'تصحيح')], max_length=20, verbose_name='السبب')),
                ('on_hand_before', models.IntegerField(verbose_name='المتوفر قبل')),
                ('on_hand_after', models.IntegerField(verbose_name='المتوفر بعد')),
                ('reserved_before', models.IntegerField(verbose_name='المحجوز قبل')),
                ('reserved_after', models.IntegerField(verbose_name='المحجوز بعد')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order', verbose_name='الطلب')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem', verbose_name='الرصيد')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('state', models.CharField(choices=[('active', 'نشط'), ('released', 'مُفرج عنه'), ('consumed', 'مُستهلك'), ('expired', 'منتهي')], default='active', max_length=16, verbose_name='الحالة')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ينتهي في')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.order', verbose_name='الطلب')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stockitem', verbose_name='الرصيد')),
            ],
            options={
                'verbose_name': 'حجز مخزون',
                'verbose_name_plural': 'حجوزات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stock_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='stock_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='stock_reserved_not_above_on_hand'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='movement_item_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['state', 'expires_at'], name='reservation_sweep_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_quantity_positive'),
        ),
    ]
