# Generated by Django 5.2.16 on 2026-08-08 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedgerReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('on_hand', 'المتوفر'), ('reserved', 'المحجوز')], max_length=16, verbose_name='الحقل')),
                ('observed_before', models.IntegerField(verbose_name='القيمة قبل')),
                ('observed_after', models.IntegerField(verbose_name='القيمة بعد')),
                ('reason', models.TextField(verbose_name='سبب التسوية')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('from_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_from', to='inventory.stockmovement', verbose_name='الحركة السابقة')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='inventory.stockitem', verbose_name='الرصيد')),
                ('to_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_to', to='inventory.stockmovement', verbose_name='الحركة التالية')),
            ],
            options={
                'verbose_name': 'تسوية سجل مخزون',
                'verbose_name_plural': 'تسويات سجل المخزون',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('from_movement', 'to_movement', 'field'), name='one_reconciliation_per_ledger_gap')],
            },
        ),
    ]
