# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('key', models.SlugField(max_length=40, unique=True, verbose_name='المفتاح')),
                ('name', models.CharField(max_length=80, verbose_name='المحافظة')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['position', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='الكود')),
                ('label', models.CharField(max_length=80, verbose_name='الاسم')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='الوصف')),
                ('icon_path', models.CharField(blank=True, default='', max_length=200, verbose_name='الأيقونة')),
                ('requires_area_eligibility', models.BooleanField(default=False, help_text='مثل التوصيل في اليوم نفسه داخل مناطق محددة.', verbose_name='يتطلب منطقة مؤهلة')),
                ('free_over_threshold', models.BooleanField(default=False, help_text='يُطبَّق على الإجمالي بعد الخصم.', verbose_name='مجاني فوق حد الشحن المجاني')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'طريقة شحن',
                'verbose_name_plural': 'طرق الشحن',
                'ordering': ['position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='المفتاح')),
                ('name', models.CharField(max_length=80, verbose_name='المنطقة')),
                ('same_day_eligible', models.BooleanField(default=False, verbose_name='يدعم التوصيل في اليوم نفسه')),
                ('installation_eligible', models.BooleanField(default=False, verbose_name='يدعم التركيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='shipping.governorate')),
            ],
            options={
                'verbose_name': 'منطقة خدمة',
                'verbose_name_plural': 'مناطق الخدمة',
                'ordering': ['governorate__position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='اسم النطاق')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('governorates', models.ManyToManyField(blank=True, related_name='zones', to='shipping.governorate', verbose_name='المحافظات')),
            ],
            options={
                'verbose_name': 'نطاق شحن',
                'verbose_name_plural': 'نطاقات الشحن',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstallationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('name', models.CharField(default='خدمة التركيب', max_length=80, verbose_name='اسم الخدمة')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الرسوم')),
                ('is_placeholder', models.BooleanField(default=True, help_text='رسوم تجريبية للتطوير فقط ولا تمثل سعرًا تجاريًا معتمدًا.', verbose_name='قيمة تطويرية غير معتمدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('governorates', models.ManyToManyField(blank=True, related_name='installation_services', to='shipping.governorate', verbose_name='المحافظات المؤهلة')),
            ],
            options={
                'verbose_name': 'خدمة تركيب',
                'verbose_name_plural': 'خدمات التركيب',
                'constraints': [models.CheckConstraint(condition=models.Q(('fee__gte', Decimal('0'))), name='installation_fee_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='السعر')),
                ('estimated_delivery_text', models.CharField(blank=True, default='', max_length=120, verbose_name='المدة المتوقعة')),
                ('is_placeholder', models.BooleanField(default=True, help_text='سعر تجريبي للتطوير فقط ولا يمثل سعرًا تجاريًا معتمدًا.', verbose_name='قيمة تطويرية غير معتمدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'سعر شحن',
                'verbose_name_plural': 'أسعار الشحن',
                'ordering': ['method__position', 'zone__position'],
                'constraints': [models.UniqueConstraint(fields=('method', 'zone'), name='unique_rate_per_method_zone'), models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0'))), name='shipping_rate_price_non_negative')],
            },
        ),
    ]
