# Generated by Django 5.2.16 on 2026-08-09 20:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='free_threshold_only',
            field=models.BooleanField(default=False, help_text='لا تُعرض هذه الطريقة إلا عندما يبلغ إجمالي الطلب حد الشحن المجاني، ولا يوجد سعر مدفوع تحت الحد. حالة الإطلاق المعتمدة.', verbose_name='مجاني فوق الحد فقط'),
        ),
        migrations.AddConstraint(
            model_name='shippingrate',
            constraint=models.CheckConstraint(condition=models.Q(('free_threshold_only', False), ('price', Decimal('0')), _connector='OR'), name='free_threshold_only_rate_is_free'),
        ),
    ]
