# Generated by Django 5.2.16 on 2026-08-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_launch_free_threshold_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='governorate',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='المحافظة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='installationservice',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='اسم الخدمة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='المنطقة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الوصف (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='الاسم (إنجليزي)'),
        ),
    ]
