"""Generate the FR → task → test traceability matrix (T-1806, SC-014).

Mechanical, not hand-maintained. A traceability matrix written by hand is a
document about what someone believed six weeks ago; this one is regenerated from
the three artefacts that actually exist:

* ``spec.md``       — the requirement IDs (FR-*, NFR-*, INV-*, SC-*).
* ``tasks.md``      — which task claims each requirement, and whether it is done.
* the test tree     — which tests name the requirement or its task.

A requirement with no test that names it is reported as a gap, not silently
omitted. That is the only property that makes the matrix worth having.

Usage::

    uv run python scripts/build_traceability.py            # write the matrix
    uv run python scripts/build_traceability.py --check    # fail on any gap
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC_DIR = ROOT / "specs" / "004-zakey-commerce-backend-admin"
SPEC = SPEC_DIR / "spec.md"
TASKS = SPEC_DIR / "tasks.md"
OUTPUT = SPEC_DIR / "traceability.md"

REQUIREMENT_RE = re.compile(r"\b((?:FR|NFR|INV|SC|ASM)-\d{3})\b")
TASK_RE = re.compile(r"\b(T-\d{4})\b")
TASK_LINE_RE = re.compile(r"^\s*- \[([ x])\] \*\*(T-\d{4})\*\*(.*)$")

TEST_ROOTS = (ROOT / "tests", ROOT / "apps")


def read_requirements() -> list[str]:
    """Requirement IDs in the order the specification defines them."""
    text = SPEC.read_text(encoding="utf-8")
    seen: list[str] = []
    for line in text.splitlines():
        # Only definition lines ("- **FR-014**: ...") introduce a requirement.
        match = re.match(r"^\s*-\s+\*\*((?:FR|NFR|INV|SC|ASM)-\d{3})\*\*", line)
        if match and match.group(1) not in seen:
            seen.append(match.group(1))
    return seen


def read_tasks() -> dict[str, dict]:
    tasks: dict[str, dict] = {}
    for line in TASKS.read_text(encoding="utf-8").splitlines():
        match = TASK_LINE_RE.match(line)
        if not match:
            continue
        done, task_id, rest = match.groups()
        tasks[task_id] = {
            "done": done == "x",
            "requirements": set(REQUIREMENT_RE.findall(rest)),
            "text": rest.strip(),
        }
    return tasks


def index_tests() -> dict[str, set[str]]:
    """token -> set of test files naming it."""
    index: dict[str, set[str]] = {}
    for root in TEST_ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("test_*.py"):
            try:
                text = path.read_text(encoding="utf-8")
            except OSError:  # pragma: no cover
                continue
            relative = str(path.relative_to(ROOT))
            for token in set(REQUIREMENT_RE.findall(text)) | set(TASK_RE.findall(text)):
                index.setdefault(token, set()).add(relative)
        for path in root.rglob("*.spec.js"):
            try:
                text = path.read_text(encoding="utf-8")
            except OSError:  # pragma: no cover
                continue
            relative = str(path.relative_to(ROOT))
            for token in set(REQUIREMENT_RE.findall(text)) | set(TASK_RE.findall(text)):
                index.setdefault(token, set()).add(relative)
    return index


def build() -> tuple[str, list[str]]:
    requirements = read_requirements()
    tasks = read_tasks()
    tests = index_tests()

    by_requirement: dict[str, set[str]] = {}
    for task_id, task in tasks.items():
        for requirement in task["requirements"]:
            by_requirement.setdefault(requirement, set()).add(task_id)

    rows = []
    gaps = []
    for requirement in requirements:
        owning = sorted(by_requirement.get(requirement, ()))
        # A test counts if it names the requirement, or names a task that claims it.
        covering: set[str] = set(tests.get(requirement, set()))
        for task_id in owning:
            covering |= tests.get(task_id, set())

        complete = all(tasks[t]["done"] for t in owning) if owning else False
        if not owning:
            gaps.append(f"{requirement}: no task claims it")
        elif not covering:
            gaps.append(f"{requirement}: no test names it or its task(s) {owning}")

        status = "✅" if (owning and covering and complete) else (
            "🚧" if owning else "❌"
        )
        rows.append(
            f"| {requirement} | {status} | {', '.join(owning) or '—'} | "
            f"{len(covering)} | {', '.join(sorted(covering)[:3]) or '—'} |"
        )

    lines = [
        "# Traceability — requirement → task → test (T-1806, SC-014)",
        "",
        "Generated by `scripts/build_traceability.py`. Do not edit by hand;",
        "regenerate it instead, or the matrix stops describing the repository.",
        "",
        "`✅` requirement claimed by completed task(s) **and** named by a test.",
        "`🚧` claimed by a task that is not finished, or finished with no test.",
        "`❌` no task claims it at all.",
        "",
        f"Requirements: **{len(requirements)}** · "
        f"Tasks: **{len(tasks)}** ({sum(1 for t in tasks.values() if t['done'])} done) · "
        f"Gaps: **{len(gaps)}**",
        "",
        "| Requirement | Status | Task(s) | Tests | Example test files |",
        "|---|---|---|---|---|",
        *rows,
    ]

    if gaps:
        lines += ["", "## Gaps", ""]
        lines += [f"- {gap}" for gap in gaps]

    return "\n".join(lines) + "\n", gaps


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Exit non-zero on any gap.")
    args = parser.parse_args()

    matrix, gaps = build()
    OUTPUT.write_text(matrix, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}  ({len(gaps)} gap(s))")
    for gap in gaps[:20]:
        print(f"  {gap}")
    if len(gaps) > 20:
        print(f"  ... and {len(gaps) - 20} more")
    return 1 if (args.check and gaps) else 0


if __name__ == "__main__":
    sys.exit(main())
