# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('archive', 'أرشفة'), ('status_change', 'تغيير حالة'), ('stock_adjust', 'تسوية مخزون'), ('price_change', 'تغيير سعر'), ('payment_record', 'تسجيل دفعة'), ('refund', 'استرجاع'), ('permission_change', 'تغيير صلاحيات'), ('login', 'دخول'), ('login_failed', 'محاولة دخول فاشلة'), ('logout', 'خروج'), ('permission_denied', 'رفض صلاحية')], max_length=32, verbose_name='الإجراء')),
                ('object_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرف السجل')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف السجل')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرف الطلب')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='بصمة IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع السجل')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='audit_object_time_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_time_idx')],
            },
        ),
    ]
