# Generated by Django 5.2.16 on 2026-08-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('archive', 'أرشفة'), ('status_change', 'تغيير حالة'), ('stock_adjust', 'تسوية مخزون'), ('price_change', 'تغيير سعر'), ('payment_record', 'تسجيل دفعة'), ('refund', 'استرجاع'), ('permission_change', 'تغيير صلاحيات'), ('login', 'دخول'), ('login_failed', 'محاولة دخول فاشلة'), ('logout', 'خروج'), ('permission_denied', 'رفض صلاحية')], db_index=True, max_length=32, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='القيم قبل وبعد التعديل مع حذف الحقول الحساسة.', verbose_name='التغييرات'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_hash',
            field=models.CharField(blank=True, default='', help_text='هاش فقط؛ لا يُخزَّن عنوان IP الخام أبدًا.', max_length=64, verbose_name='بصمة عنوان IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف العنصر'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان العنصر'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الطلب'),
        ),
    ]
