# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='المعرف')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='الشعار')),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=16, verbose_name='الحالة')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='نُشر في')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='أُرشف في')),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='المعرف')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('promotion_eyebrow', models.CharField(blank=True, default='', max_length=80, verbose_name='عنوان فرعي')),
                ('promotion_tone', models.CharField(blank=True, default='', max_length=40, verbose_name='النغمة')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'المجموعات',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=16, verbose_name='الحالة')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='نُشر في')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='أُرشف في')),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='المعرف')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('kind', models.CharField(blank=True, default='', max_length=40, verbose_name='النوع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='الصورة')),
                ('legacy_image_path', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('seo_title', models.CharField(blank=True, default='', max_length=160, verbose_name='عنوان SEO')),
                ('seo_description', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف SEO')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='التصنيف الأعلى')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=16, verbose_name='الحالة')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='نُشر في')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='أُرشف في')),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='المعرف')),
                ('name', models.CharField(max_length=160, verbose_name='الاسم')),
                ('short_description', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف مختصر')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('badge', models.CharField(blank=True, default='', max_length=60, verbose_name='الشارة')),
                ('instalment_message', models.CharField(blank=True, default='', max_length=255, verbose_name='رسالة التقسيط')),
                ('same_day_supported', models.BooleanField(default=False, verbose_name='يدعم التوصيل في اليوم نفسه')),
                ('installation_supported', models.BooleanField(default=False, verbose_name='يدعم التركيب')),
                ('rating_average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='متوسط التقييم')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('seo_title', models.CharField(blank=True, default='', max_length=160, verbose_name='عنوان SEO')),
                ('seo_description', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف SEO')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='العلامة التجارية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'منتج داخل مجموعة',
                'verbose_name_plural': 'منتجات المجموعات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='collections', through='catalog.CollectionProduct', to='catalog.product', verbose_name='المنتجات'),
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('legacy_id', models.CharField(blank=True, default='', max_length=64)),
                ('label', models.CharField(max_length=120, verbose_name='الاسم')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='الملف')),
                ('legacy_path', models.CharField(blank=True, default='', max_length=255)),
                ('file_format', models.CharField(default='PDF', max_length=16, verbose_name='الصيغة')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مستند منتج',
                'verbose_name_plural': 'مستندات المنتجات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('key', models.SlugField(max_length=60, verbose_name='المفتاح')),
                ('label', models.CharField(max_length=120, verbose_name='الاسم')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='الوصف')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'المميزات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('legacy_id', models.CharField(blank=True, default='', max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة')),
                ('legacy_path', models.CharField(blank=True, default='', help_text='مسار الأصل داخل static؛ يحافظ على ثبات الاستيراد.', max_length=255, verbose_name='المسار الأصلي')),
                ('alt', models.CharField(max_length=200, verbose_name='النص البديل')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='العرض')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='الارتفاع')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='catalog.product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='catalog.product')),
            ],
            options={
                'verbose_name': 'منتج ذو صلة',
                'verbose_name_plural': 'المنتجات ذات الصلة',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='catalog.ProductRelation', to='catalog.product', verbose_name='منتجات ذات صلة'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('finish_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرف اللون')),
                ('finish_label', models.CharField(blank=True, default='', max_length=80, verbose_name='اللون')),
                ('swatch_hex', models.CharField(blank=True, default='', max_length=9, verbose_name='لون العينة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر (شامل الضريبة)')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر قبل الخصم')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'خيار منتج',
                'verbose_name_plural': 'خيارات المنتجات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('legacy_id', models.CharField(blank=True, default='', max_length=64)),
                ('label', models.CharField(max_length=120, verbose_name='المجموعة')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_groups', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مجموعة مواصفات',
                'verbose_name_plural': 'مجموعات المواصفات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='البند')),
                ('value', models.CharField(max_length=255, verbose_name='القيمة')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.specificationgroup', verbose_name='المجموعة')),
            ],
            options={
                'verbose_name': 'مواصفة',
                'verbose_name_plural': 'المواصفات',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='collectionproduct',
            constraint=models.UniqueConstraint(fields=('collection', 'product'), name='unique_product_per_collection'),
        ),
        migrations.AddIndex(
            model_name='productfeature',
            index=models.Index(fields=['key'], name='feature_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='productfeature',
            constraint=models.UniqueConstraint(fields=('product', 'key'), name='unique_feature_key_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.UniqueConstraint(fields=('from_product', 'to_product'), name='unique_product_relation'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.CheckConstraint(condition=models.Q(('from_product', models.F('to_product')), _negated=True), name='product_relation_not_self'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'published_at'], name='product_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='product_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique_variant_sku'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='unique_default_variant_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', Decimal('0'))), name='variant_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('compare_at_price__isnull', True), ('compare_at_price__gt', models.F('price')), _connector='OR'), name='variant_compare_at_price_above_price'),
        ),
    ]
