# Generated by Django 5.2.16 on 2026-08-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='النص البديل'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_height',
            field=models.PositiveIntegerField(default=0, verbose_name='الارتفاع'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_width',
            field=models.PositiveIntegerField(default=0, verbose_name='العرض'),
        ),
    ]
