# Generated by Django 5.2.16 on 2026-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_image_alt_category_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='notice',
            field=models.CharField(blank=True, default='', help_text='سطر توضيحي يظهر أسفل اسم المستند في صفحة المنتج.', max_length=255, verbose_name='تنويه'),
        ),
    ]
