# Generated by Django 5.2.16 on 2026-08-08 13:14

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productdocument_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', validators=[apps.core.uploads.validate_image_upload], verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[apps.core.uploads.validate_image_upload], verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[apps.core.uploads.validate_document_upload], verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.core.uploads.validate_image_upload], verbose_name='الصورة'),
        ),
    ]
