# Generated by Django 5.2.16 on 2026-08-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_brand_logo_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='الوصف (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='النص البديل (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='category',
            name='kind_en',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='النوع (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='وصف SEO (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='عنوان SEO (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='الوصف (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='promotion_eyebrow_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='عنوان فرعي (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_en',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='الشارة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='الوصف (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='instalment_message_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='رسالة التقسيط (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='وصف SEO (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='عنوان SEO (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='وصف مختصر (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='notice_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='تنويه (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الوصف (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='النص البديل (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='finish_label_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='اللون (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='specificationgroup',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='المجموعة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='specificationitem',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='البند (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='specificationitem',
            name='value_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='القيمة (إنجليزي)'),
        ),
    ]
