# Generated by Django 5.2.16 on 2026-08-04 13:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('author_name', models.CharField(max_length=120, verbose_name='اسم الكاتب')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('title', models.CharField(blank=True, default='', max_length=160, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='النص')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'منشور'), ('rejected', 'مرفوض')], default='pending', max_length=16, verbose_name='الحالة')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='شراء موثّق')),
                ('staff_response', models.TextField(blank=True, default='', verbose_name='رد الفريق')),
                ('placement', models.JSONField(blank=True, default=list, help_text='مثل ["product", "home"] كما في بيانات الواجهة.', verbose_name='أماكن العرض')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='روجع في')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='accounts.customerprofile', verbose_name='العميل')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'status'], name='review_product_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5'), models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('product', 'customer'), name='unique_review_per_customer_product')],
            },
        ),
    ]
