# Generated by Django 5.2.16 on 2026-08-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_name_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='اسم الكاتب (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='review',
            name='body_en',
            field=models.TextField(blank=True, default='', verbose_name='النص (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='review',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='العنوان (إنجليزي)'),
        ),
    ]
